<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>
    <meta http-equiv="Content-type" content="text/html;charset=utf-8" />
    <style>
        table { border-collapse: collapse; width: 100%; border: 1pt solid #000; }
        th { background-color: #cbd5e1; font-weight: bold; border: 1pt solid #000; padding: 10px 5px; font-size: 11pt; font-family: Arial, sans-serif; text-align: center; }
        td { border: 1pt solid #cbd5e1; padding: 8px 5px; vertical-align: top; font-size: 10pt; font-family: Arial, sans-serif; text-align: center; }
        td.text-left { text-align: left; }
        .header-title { font-size: 16pt; font-weight: bold; text-align: center; font-family: Arial, sans-serif; text-decoration: underline; }
        .bold { font-weight: bold; }
        @page {
            margin: 0.5in;
            mso-header-margin: 0.5in;
            mso-footer-margin: 0.5in;
            mso-page-orientation: landscape;
        }
    </style>
</head>
<body>
    <table>
        <tr><td colspan="12" class="header-title" style="border:none;">{{ $mainHeading }}</td></tr>
        <tr><td colspan="12" style="border:none; height:10px;"></td></tr>
        
        <colgroup>
            <col style="width: 120pt;"> <!-- Seat -->
            <col style="width: 60pt;"> <!-- Total Petitions -->
            <col style="width: 60pt;"> <!-- New Petitions -->
            <col style="width: 60pt;"> <!-- Forwarded Petitions -->
            <col style="width: 60pt;"> <!-- VR Received -->
            <col style="width: 60pt;"> <!-- Total Decisions -->
            <col style="width: 40pt;"> <!-- PE -->
            <col style="width: 40pt;"> <!-- SC -->
            <col style="width: 40pt;"> <!-- QV -->
            <col style="width: 40pt;"> <!-- ICell -->
            <col style="width: 50pt;"> <!-- Closed -->
            <col style="width: 60pt;"> <!-- Sent Govt -->
        </colgroup>
        <thead>
            <tr>
                <th rowspan="2">Seat</th>
                <th rowspan="2">Total Petitions</th>
                <th rowspan="2">New Petitions</th>
                <th rowspan="2">Forwarded Petitions</th>
                <th rowspan="2">Verification Reports Received</th>
                <th colspan="7">Final Decisions</th>
            </tr>
            <tr>
                <th>Total</th>
                <th>PE</th>
                <th>SC</th>
                <th>QV</th>
                <th>ICell</th>
                <th>Closed</th>
                <th>Sent Govt</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($seats as $seat)
                <tr>
                    <td class="text-left"><span class="bold">{{ $seat->seat_name }}</span></td>
                    <td>{{ $seat->petitions_all_count }}</td>
                    <td>{{ $seat->petitions_received_count }}</td>
                    <td>{{ $seat->forwardings_out_count }}</td>
                    <td>{{ $seat->vr_received_count }}</td>
                    <td class="bold">{{ $seat->decisions_made_count }}</td>
                    <td>{{ $seat->decisions_pe_count }}</td>
                    <td>{{ $seat->decisions_sc_count }}</td>
                    <td>{{ $seat->decisions_qv_count }}</td>
                    <td>{{ $seat->decisions_icell_count }}</td>
                    <td>{{ $seat->decisions_closed_count }}</td>
                    <td>{{ $seat->decisions_sent_count }}</td>
                </tr>
            @endforeach

            @if ($seats->isNotEmpty())
                <tr class="bold" style="background-color: #f1f5f9;">
                    <td class="text-left">TOTAL</td>
                    <td>{{ $seats->sum('petitions_all_count') }}</td>
                    <td>{{ $seats->sum('petitions_received_count') }}</td>
                    <td>{{ $seats->sum('forwardings_out_count') }}</td>
                    <td>{{ $seats->sum('vr_received_count') }}</td>
                    <td>{{ $seats->sum('decisions_made_count') }}</td>
                    <td>{{ $seats->sum('decisions_pe_count') }}</td>
                    <td>{{ $seats->sum('decisions_sc_count') }}</td>
                    <td>{{ $seats->sum('decisions_qv_count') }}</td>
                    <td>{{ $seats->sum('decisions_icell_count') }}</td>
                    <td>{{ $seats->sum('decisions_closed_count') }}</td>
                    <td>{{ $seats->sum('decisions_sent_count') }}</td>
                </tr>
            @endif
        </tbody>
    </table>
    <div style="margin-top: 15px; font-size: 8pt; text-align: right; font-family: Arial, sans-serif;">Generated by CPSP System on {{ now()->format('Y-m-d H:i:s') }}</div>
</body>
</html>
